controller_list:
  - name: fake_stand_controller
    type: $(arg fake_execution_type)
    joints:
      []
  - name: fake_tool_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses per group
  - group: tool
    pose: top